apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  namespace: argo-nodejsdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs-container
          image: akmabrdockerid/my-node-application:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: argo-nodejsdemo
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080

