apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: argo-nodejsdemo
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      #NodePort: 30080